import { launch, attachLogs, BASE } from './util.mjs';
const b = await launch();
const p = await b.newPage({ viewport: { width: 1100, height: 760 } });
const logs = attachLogs(p);
await p.goto(BASE); await p.waitForTimeout(800);
await p.click('text=CREATE VISUAL'); await p.waitForFunction(() => document.querySelector('.app')?.dataset.screen === 'studio', null, { timeout: 45000 });
await p.waitForTimeout(2000);
await p.click('.tabs button:has-text("MOTION")'); await p.waitForTimeout(2500);
const info = async () => p.evaluate(() => ({ wires: document.querySelectorAll('.bay path.wire').length, map: window.__studio ? null : null }));
await p.locator('.bay').scrollIntoViewIfNeeded(); await p.waitForTimeout(600);
const before = (await info()).wires;
const src = await p.locator('.bay-col.src .node').nth(0).boundingBox();
const tgt = await p.locator('.bay-col.tgt .node[data-target="camera"]').boundingBox();
console.log('src', JSON.stringify(src), 'tgt', JSON.stringify(tgt), 'srcLabel', await p.locator('.bay-col.src .node').nth(0).textContent());
const existing = await p.evaluate(() => [...document.querySelectorAll('.bay path.wire')].map((w) => w.dataset.src + '>' + w.dataset.dst));
console.log('existing wires', existing.join(', '));
await p.mouse.move(src.x + 20, src.y + src.height / 2); await p.mouse.down();
await p.mouse.move(src.x + 60, src.y + 40, { steps: 4 }); await p.mouse.move(tgt.x + 20, tgt.y + tgt.height / 2, { steps: 8 });
console.log('mid-drag rubber band:', await p.locator('.bay-drag').count());
console.log('element under cursor:', await p.evaluate(([x, y]) => { const e = document.elementFromPoint(x, y); return e && (e.dataset.target || e.className || e.tagName); }, [tgt.x + 20, tgt.y + tgt.height / 2]));
await p.mouse.up(); await p.waitForTimeout(800);
const after = await p.evaluate(() => [...document.querySelectorAll('.bay path.wire')].map((w) => w.dataset.src + '>' + w.dataset.dst));
console.log('wires', before, '→', after.length, after.join(', '));
console.log(logs.filter((l) => !/ERR_FAILED/.test(l)).slice(0, 5).join('\n'));
await b.close();
